// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ooXIaUigJgjIcV8nLzMsQSd-Hg8BiHo',
    appId: '1:266237587921:web:401866eed0dbbc40a8f0f0',
    messagingSenderId: '266237587921',
    projectId: 'ct240doan-49e91',
    authDomain: 'ct240doan-49e91.firebaseapp.com',
    storageBucket: 'ct240doan-49e91.appspot.com',
    measurementId: 'G-TS7FHECTF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNx6K2RDXl6U0MwottOJTSdEDHZC10xZs',
    appId: '1:266237587921:android:8371cca73bfaf97aa8f0f0',
    messagingSenderId: '266237587921',
    projectId: 'ct240doan-49e91',
    storageBucket: 'ct240doan-49e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskmQNk4Q12VH3RAqpuW9BfAFJOunY8Gs',
    appId: '1:266237587921:ios:3685b1ddac49074ca8f0f0',
    messagingSenderId: '266237587921',
    projectId: 'ct240doan-49e91',
    storageBucket: 'ct240doan-49e91.appspot.com',
    androidClientId: '266237587921-ua53ha5asl99eng6fvcvtuifqoqlmoi8.apps.googleusercontent.com',
    iosClientId: '266237587921-5bijjibdj7g1l6f5lr4b9dgls3jstkqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ct240Doan',
  );
}
